// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/4/26 18:13:06
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/plugins/**/*.{js,ts,mjs}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/composables/**/*.{js,ts,mjs}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/utils/**/*.{js,ts,mjs}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","Z:/DocumentinZ/00MyProject/VidSumAI/.worktrees/preview-download/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;